package view;

import controller.Controller;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        control = new Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario_label = new javax.swing.JLabel();
        usuario_txtfield = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastro_menuitem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        login_menuitem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        update_menuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete");

        usuario_label.setText("Usuario:");

        usuario_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_txtfieldActionPerformed(evt);
            }
        });

        delete_btn.setText("Deletar");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastro");

        cadastro_menuitem.setText("Cadastrar");
        cadastro_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_menuitemActionPerformed(evt);
            }
        });
        jMenu1.add(cadastro_menuitem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Login");

        login_menuitem.setText("Logar");
        login_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_menuitemActionPerformed(evt);
            }
        });
        jMenu2.add(login_menuitem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Update");

        update_menuitem.setText("Atualizar");
        update_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_menuitemActionPerformed(evt);
            }
        });
        jMenu3.add(update_menuitem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addComponent(usuario_label)
                .addGap(18, 18, 18)
                .addComponent(usuario_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(delete_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario_label))
                .addGap(18, 18, 18)
                .addComponent(delete_btn)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        control.DeleteAluno();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void usuario_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_txtfieldActionPerformed

    private void cadastro_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_menuitemActionPerformed
       Cadastro c = new Cadastro();
       c.setVisible(true);
    }//GEN-LAST:event_cadastro_menuitemActionPerformed

    private void login_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_menuitemActionPerformed
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_login_menuitemActionPerformed

    private void update_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_menuitemActionPerformed
        Update u = new Update();
        u.setVisible(true);
    }//GEN-LAST:event_update_menuitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    public Controller getControl() {
        return control;
    }

    public void setControl(Controller control) {
        this.control = control;
    }

    public JButton getDelete_btn() {
        return delete_btn;
    }

    public void setDelete_btn(JButton delete_btn) {
        this.delete_btn = delete_btn;
    }

    public JLabel getUsuario_label() {
        return usuario_label;
    }

    public void setUsuario_label(JLabel usuario_label) {
        this.usuario_label = usuario_label;
    }

    public JTextField getUsuario_txtfield() {
        return usuario_txtfield;
    }

    public void setUsuario_txtfield(JTextField usuario_txtfield) {
        this.usuario_txtfield = usuario_txtfield;
    }
    
    
    private Controller control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastro_menuitem;
    private javax.swing.JButton delete_btn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem login_menuitem;
    private javax.swing.JMenuItem update_menuitem;
    private javax.swing.JLabel usuario_label;
    private javax.swing.JTextField usuario_txtfield;
    // End of variables declaration//GEN-END:variables
}
