package view;
import controller.Controller;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        control = new Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        usuario_label = new javax.swing.JLabel();
        senha_label = new javax.swing.JLabel();
        usuario_txtfield = new javax.swing.JTextField();
        senha_txtfield = new javax.swing.JTextField();
        login_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastro_menuitem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        update_menuitem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        delete_menuitem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        usuario_label.setText("Usuario:");

        senha_label.setText("Senha:");

        login_btn.setText("Logar");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastro");

        cadastro_menuitem.setText("Cadastrar");
        cadastro_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_menuitemActionPerformed(evt);
            }
        });
        jMenu1.add(cadastro_menuitem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Update");

        update_menuitem.setText("Atualizar");
        update_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_menuitemActionPerformed(evt);
            }
        });
        jMenu2.add(update_menuitem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Delete");

        delete_menuitem.setText("Deletar");
        delete_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_menuitemActionPerformed(evt);
            }
        });
        jMenu3.add(delete_menuitem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(senha_label)
                            .addComponent(usuario_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario_txtfield)
                            .addComponent(senha_txtfield, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(login_btn)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario_label)
                    .addComponent(usuario_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha_label)
                    .addComponent(senha_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(login_btn)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        control.consultarAluno();
    }//GEN-LAST:event_login_btnActionPerformed

    private void cadastro_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_menuitemActionPerformed
        Cadastro c = new Cadastro();
        c.setVisible(true);
    }//GEN-LAST:event_cadastro_menuitemActionPerformed

    private void update_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_menuitemActionPerformed
       Update u = new Update();
       u.setVisible(true);
    }//GEN-LAST:event_update_menuitemActionPerformed

    private void delete_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_menuitemActionPerformed
        Delete d = new Delete();
        d.setVisible(true);
    }//GEN-LAST:event_delete_menuitemActionPerformed

    public Controller getControl() {
        return control;
    }

    public void setControl(Controller control) {
        this.control = control;
    }

    public JButton getLogin_btn() {
        return login_btn;
    }

    public void setLogin_btn(JButton login_btn) {
        this.login_btn = login_btn;
    }

    public JLabel getSenha_label() {
        return senha_label;
    }

    public void setSenha_label(JLabel senha_label) {
        this.senha_label = senha_label;
    }

    public JTextField getSenha_txtfield() {
        return senha_txtfield;
    }

    public void setSenha_txtfield(JTextField senha_txtfield) {
        this.senha_txtfield = senha_txtfield;
    }

    public JLabel getUsuario_label() {
        return usuario_label;
    }

    public void setUsuario_label(JLabel usuario_label) {
        this.usuario_label = usuario_label;
    }

    public JTextField getUsuario_txtfield() {
        return usuario_txtfield;
    }

    public void setUsuario_txtfield(JTextField usuario_txtfield) {
        this.usuario_txtfield = usuario_txtfield;
    }

    private Controller control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastro_menuitem;
    private javax.swing.JMenuItem delete_menuitem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel senha_label;
    private javax.swing.JTextField senha_txtfield;
    private javax.swing.JMenuItem update_menuitem;
    private javax.swing.JLabel usuario_label;
    private javax.swing.JTextField usuario_txtfield;
    // End of variables declaration//GEN-END:variables
}
