package view;
import controller.Controller;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextField;
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        control = new Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome_label = new javax.swing.JLabel();
        usuario_label = new javax.swing.JLabel();
        senha_label = new javax.swing.JLabel();
        nome_txtfield = new javax.swing.JTextField();
        usuario_txtfield = new javax.swing.JTextField();
        senha_txtfield = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        usuarioantigo_label = new javax.swing.JLabel();
        usuarioantigo_txtfield = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastro_menuitem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        login_menuitem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        delete_menuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update");

        nome_label.setText("Nome:");

        usuario_label.setText("Usuario:");

        senha_label.setText("Senha:");

        nome_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtfieldActionPerformed(evt);
            }
        });

        usuario_txtfield.setToolTipText("");

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        usuarioantigo_label.setText("Usuario antigo:");

        jMenu1.setText("Cadastro");

        cadastro_menuitem.setText("Cadastrar");
        cadastro_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_menuitemActionPerformed(evt);
            }
        });
        jMenu1.add(cadastro_menuitem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Login");

        login_menuitem.setText("Logar");
        login_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_menuitemActionPerformed(evt);
            }
        });
        jMenu2.add(login_menuitem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Delete");

        delete_menuitem.setText("Deletar");
        delete_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_menuitemActionPerformed(evt);
            }
        });
        jMenu3.add(delete_menuitem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(senha_label)
                            .addComponent(usuario_label)
                            .addComponent(nome_label)
                            .addComponent(usuarioantigo_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome_txtfield)
                            .addComponent(usuario_txtfield)
                            .addComponent(senha_txtfield)
                            .addComponent(usuarioantigo_txtfield, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(update_btn)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioantigo_label)
                    .addComponent(usuarioantigo_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_label)
                    .addComponent(nome_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario_label)
                    .addComponent(usuario_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha_label)
                    .addComponent(senha_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(update_btn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtfieldActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
       control.UpdateAluno("senha");
       control.UpdateAluno("nome");
       control.UpdateAluno("usuario");
    }//GEN-LAST:event_update_btnActionPerformed

    private void cadastro_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_menuitemActionPerformed
        Cadastro c = new Cadastro();
        c.setVisible(true);
    }//GEN-LAST:event_cadastro_menuitemActionPerformed

    private void login_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_menuitemActionPerformed
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_login_menuitemActionPerformed

    private void delete_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_menuitemActionPerformed
        Delete d = new Delete();
        d.setVisible(true);
    }//GEN-LAST:event_delete_menuitemActionPerformed

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return cadastro_menuitem;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.cadastro_menuitem = jMenuItem1;
    }

    public JLabel getUsuarioantigo_label() {
        return usuarioantigo_label;
    }

    public void setUsuarioantigo_label(JLabel usuarioantigo_label) {
        this.usuarioantigo_label = usuarioantigo_label;
    }

    public JTextField getUsuarioantigo_txtfield() {
        return usuarioantigo_txtfield;
    }

    public void setUsuarioantigo_txtfield(JTextField usuarioantigo_txtfield) {
        this.usuarioantigo_txtfield = usuarioantigo_txtfield;
    }
       
    public Controller getControl() {
        return control;
    }

    public void setControl(Controller control) {
        this.control = control;
    }

    public JLabel getNome_label() {
        return nome_label;
    }

    public void setNome_label(JLabel nome_label) {
        this.nome_label = nome_label;
    }

    public JTextField getNome_txtfield() {
        return nome_txtfield;
    }

    public void setNome_txtfield(JTextField nome_txtfield) {
        this.nome_txtfield = nome_txtfield;
    }

    public JLabel getSenha_label() {
        return senha_label;
    }

    public void setSenha_label(JLabel senha_label) {
        this.senha_label = senha_label;
    }

    public JTextField getSenha_txtfield() {
        return senha_txtfield;
    }

    public void setSenha_txtfield(JTextField senha_txtfield) {
        this.senha_txtfield = senha_txtfield;
    }

    public JButton getUpdate_btn() {
        return update_btn;
    }

    public void setUpdate_btn(JButton update_btn) {
        this.update_btn = update_btn;
    }

    public JLabel getUsuario_label() {
        return usuario_label;
    }

    public void setUsuario_label(JLabel usuario_label) {
        this.usuario_label = usuario_label;
    }

    public JTextField getUsuario_txtfield() {
        return usuario_txtfield;
    }

    /**
     * @param args the command line arguments
     */
    public void setUsuario_txtfield(JTextField usuario_txtfield) {
        this.usuario_txtfield = usuario_txtfield;
    }

    
    
    private Controller control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastro_menuitem;
    private javax.swing.JMenuItem delete_menuitem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem login_menuitem;
    private javax.swing.JLabel nome_label;
    private javax.swing.JTextField nome_txtfield;
    private javax.swing.JLabel senha_label;
    private javax.swing.JTextField senha_txtfield;
    private javax.swing.JButton update_btn;
    private javax.swing.JLabel usuario_label;
    private javax.swing.JTextField usuario_txtfield;
    private javax.swing.JLabel usuarioantigo_label;
    private javax.swing.JTextField usuarioantigo_txtfield;
    // End of variables declaration//GEN-END:variables
}
